#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# SparkNode — EC2 user-data (cloud-init) bootstrap script
# Runs once on first boot. Installs Docker, clones repo,
# writes env files, starts Docker Compose with Traefik.
# ──────────────────────────────────────────────────────────────
set -euo pipefail
exec > >(tee /var/log/sparknode-init.log) 2>&1

echo ">>> SparkNode cloud-init starting — $(date -u)"

# ─── Templated variables from Terraform ──────────────────────
PROJECT_NAME="${project_name}"
DOMAIN="${domain}"
ACME_EMAIL="${acme_email}"
POSTGRES_PASSWORD="${postgres_password}"
APP_SECRET_KEY="${app_secret_key}"
SMTP_HOST="${smtp_host}"
SMTP_PORT="${smtp_port}"
SMTP_USER="${smtp_user}"
SMTP_PASSWORD="${smtp_password}"
APP_VERSION="${app_version}"
GITHUB_REPO="${github_repo}"
GITHUB_DEPLOY_TOKEN="${github_deploy_token}"
ENVIRONMENT="${environment}"

APP_DIR="/opt/$PROJECT_NAME"

# ─── 1. System packages ─────────────────────────────────────
apt-get update -y
apt-get upgrade -y
apt-get install -y \
  ca-certificates curl gnupg lsb-release \
  apt-transport-https software-properties-common \
  git jq unzip fail2ban ufw htop

# ─── 2. Install Docker Engine ────────────────────────────────
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
  gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
  https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update -y
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

systemctl enable docker
systemctl start docker
usermod -aG docker ubuntu

# ─── 3. Firewall ─────────────────────────────────────────────
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable

# ─── 4. Clone repository ────────────────────────────────────
if [ -n "$GITHUB_REPO" ]; then
  CLONE_URL="$GITHUB_REPO"
  if [ -n "$GITHUB_DEPLOY_TOKEN" ]; then
    # Insert token into HTTPS url: https://TOKEN@github.com/...
    CLONE_URL=$(echo "$GITHUB_REPO" | sed "s|https://|https://$GITHUB_DEPLOY_TOKEN@|")
  fi
  git clone --depth 1 "$CLONE_URL" "$APP_DIR"
else
  mkdir -p "$APP_DIR"
  echo "WARNING: No github_repo specified. You must manually copy files to $APP_DIR"
fi

# Create deployment / traefik directories
mkdir -p "$APP_DIR/traefik/acme"
mkdir -p "$APP_DIR/traefik/dynamic"
mkdir -p "$APP_DIR/backups"

# ─── 5. Write production .env ────────────────────────────────
cat > "$APP_DIR/.env" <<ENVEOF
# SparkNode Production Environment — Auto-generated by Terraform
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
PROJECT_NAME=$PROJECT_NAME
ENVIRONMENT=$ENVIRONMENT
DOMAIN=$DOMAIN
ACME_EMAIL=$ACME_EMAIL
APP_VERSION=$APP_VERSION

# PostgreSQL
POSTGRES_USER=sparknode
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=sparknode

# Backend
DATABASE_URL=postgresql://sparknode:$POSTGRES_PASSWORD@postgres:5432/sparknode
APP_DATABASE_URL=postgresql://sparknode:$POSTGRES_PASSWORD@postgres:5432/sparknode
SECRET_KEY=$APP_SECRET_KEY
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60
CORS_ORIGINS=https://$DOMAIN

# SMTP
SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_USER=$SMTP_USER
SMTP_PASSWORD=$SMTP_PASSWORD
SMTP_FROM=no-reply@$DOMAIN
SMTP_USE_TLS=true

# Celery
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0
ENVEOF

chmod 600 "$APP_DIR/.env"

# ─── 6. Write Traefik static config ─────────────────────────
cat > "$APP_DIR/traefik/traefik.yml" <<'TRAEFIKEOF'
api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${ACME_EMAIL}"
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: sparknode-network
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100
TRAEFIKEOF

# Patch the ACME email into traefik.yml
sed -i "s|\$${ACME_EMAIL}|$ACME_EMAIL|g" "$APP_DIR/traefik/traefik.yml"

# ─── 7. Write Traefik dynamic middleware config ──────────────
cat > "$APP_DIR/traefik/dynamic/middlewares.yml" <<'MIDEOF'
http:
  middlewares:
    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        referrerPolicy: "strict-origin-when-cross-origin"
        customResponseHeaders:
          X-Powered-By: ""
          Server: ""

    rate-limit:
      rateLimit:
        average: 100
        burst: 200
        period: "1m"

    compress:
      compress:
        excludedContentTypes:
          - "text/event-stream"
MIDEOF

# ─── 8. Write production docker-compose ──────────────────────
# Copy from deployment dir if repo was cloned, otherwise generate
if [ -f "$APP_DIR/deployment_sparknode/docker/docker-compose.prod.yml" ]; then
  cp "$APP_DIR/deployment_sparknode/docker/docker-compose.prod.yml" "$APP_DIR/docker-compose.prod.yml"
fi

# ─── 9. Build frontend production assets ─────────────────────
if [ -d "$APP_DIR/frontend" ]; then
  echo ">>> Building frontend assets..."
  cd "$APP_DIR/frontend"

  # Use a temporary Node container to build
  docker run --rm \
    -v "$APP_DIR/frontend:/app" \
    -w /app \
    -e VITE_API_URL="https://$DOMAIN" \
    node:20-alpine \
    sh -c "npm ci && npm run build"

  cd "$APP_DIR"
fi

# ─── 10. Copy production compose if not already there ────────
if [ ! -f "$APP_DIR/docker-compose.prod.yml" ] && [ -f "$APP_DIR/deployment_sparknode/docker/docker-compose.prod.yml" ]; then
  cp "$APP_DIR/deployment_sparknode/docker/docker-compose.prod.yml" "$APP_DIR/docker-compose.prod.yml"
fi

# ─── 11. Start services ─────────────────────────────────────
cd "$APP_DIR"
docker compose -f docker-compose.prod.yml --env-file .env up -d --build

# ─── 12. Set up daily database backup cron ───────────────────
cat > /etc/cron.d/sparknode-backup <<CRONEOF
# Daily PostgreSQL backup at 02:00 UTC
0 2 * * * root docker exec ${PROJECT_NAME}-db pg_dump -U sparknode sparknode | gzip > $APP_DIR/backups/sparknode-\$(date +\%Y\%m\%d-\%H\%M\%S).sql.gz && find $APP_DIR/backups -name "*.sql.gz" -mtime +7 -delete
CRONEOF
chmod 644 /etc/cron.d/sparknode-backup

# ─── 13. Log rotation for Traefik ───────────────────────────
cat > /etc/logrotate.d/traefik <<LOGEOF
/opt/$PROJECT_NAME/traefik/logs/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0644 root root
    postrotate
        docker kill --signal=USR1 ${PROJECT_NAME}-traefik 2>/dev/null || true
    endscript
}
LOGEOF

echo ">>> SparkNode cloud-init complete — $(date -u)"
echo ">>> Application should be available at https://$DOMAIN"
